---
- name: Example
  hosts: all

  tasks:
    - name: Test hosts can execute tasks
      ansible.builtin.ping:

    - name: Set authorized keys taken from url
      ansible.posix.authorized_key:
        user: root
        state: present
        key: https://github.com/jcmdln.keys
