---
- name: Example
  hosts: all

  tasks:
    - name: Test hosts can execute tasks
      ansible.builtin.ping:

    - name: Gather information about active zones
      ansible.posix.firewalld_info:
        active_zones: true
      register: result

    - name: Print default zone for debugging
      ansible.builtin.debug:
        var: result.firewalld_info.default_zone
